terminal = "kitty"
arguments = [
  '--single-instance',
  '--instance-group',
  'fzfmenu',
  '--title',
  'fzfmenu',
  '-c',
  '/Users/inogai/.config/fzfmenu/kitty.conf'
]

fzf_arguments = [
]

[[plugins]]
name = "app_launcher"
description = "Launch applications based on your desktop environment."
prefix = ""
picker = "fd -d2 -L '\\.app$' /Applications $HOME/Applications /System/Applications -x echo {/}"
runner = "/usr/bin/open -a '{}'"

[[plugins]]
name = "focus"
description = "Focus an aerospace window"
prefix = "fo "
picker = "aerospace list-windows --all"
runner = "~/.config/fzfmenu/focus-window.ts '{}'"
