#!/usr/bin/env bash

set -euo pipefail

show_help() {
  echo "Usage: noti [-t TITLE] <message>"
  echo ""
  echo "Options:"
  echo "  -t TITLE    Set the notification title"
  echo "  -h          Show this help message"
  echo ""
  echo "Arguments:"
  echo "  message     Notification content (default: \"Notification\")"
  echo ""
  echo "Examples:"
  echo "  noti \"Hello World\""
  echo "  noti -t \"Alert\" \"Something happened\""
}

title="Default"
message="Notification"

while getopts "t:h" opt; do
  case $opt in
    t) title="$OPTARG" ;;
    h) show_help; exit 0 ;;
    *) show_help; exit 1 ;;
  esac
done

shift $((OPTIND-1))

if [ $# -ge 1 ]; then
  message="$1"
fi

osascript -e "display notification \"$message\" with title \"$title\""
